testFeignConfig: SUCCESS

# 配置日志
logging:
  level:
    com.huan.study.feign: debug

  # feign和hystrix的配置
feign:
  hystrix:
    enabled: true # 启用hystrix
  client:
    config:
      default:
        loggerLevel: full # feign的日志级别